# Generated by Django 5.0.4 on 2024-05-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_event_color_alter_event_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
