# Generated by Django 5.0.4 on 2024-05-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_customuser_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
